
public class MonitorGUI extends javax.swing.JFrame {

	public MonitorController monitorcontroller;
	private WholeSystem wholeGUI;

	public MonitorGUI(WholeSystem wholeGUI) {
		initComponents();
		this.monitorcontroller = new MonitorController(this);
		this.wholeGUI = wholeGUI;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

	}
}