import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class SimulatorGUI extends javax.swing.JFrame {

	private SimulatorController simulatorcontroller;

	public SimulatorGUI(SimulatorController simulatorcontroller) {
		initComponents();
		this.simulatorcontroller = simulatorcontroller;
		getContentPane().setLayout(null);
		
		JButton btnNewButton = new JButton("New button");
		btnNewButton.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				
			}
		});
		btnNewButton.setBounds(60, 317, 89, 23);
		getContentPane().add(btnNewButton);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")                        
	private void initComponents() {

	}                 
	public void test(){

	}
}
