
public class SimulatorGUI extends javax.swing.JFrame {

	private SimulatorController simulatorcontroller;
	private WholeSystem wholeGUI;

	/**
	 * Creates new form SimulatorGUI
	 */

	public SimulatorGUI(WholeSystem wholeGUI) {
		initComponents();
		this.simulatorcontroller = new SimulatorController(this);
		this.wholeGUI = wholeGUI;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")                        
	private void initComponents() {

	}                 
}
