
public class SimulatorGUI extends javax.swing.JFrame {

	private SimulatorController simulatorcontroller;

	public SimulatorGUI(SimulatorController simulatorcontroller) {
		initComponents();
		this.simulatorcontroller = simulatorcontroller;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")                        
	private void initComponents() {

	}                 
	public void test(){

	}
}
